file_name: advanced_excel_file.xlsx
cell_formats:
  - format_name: normal_fmt
    font_size: 11
    horizontal_alignment: center
    vertical_alignment: center
    line_break: false
  - format_name: small_fmt
    font_size: 8
    horizontal_alignment: left
    vertical_alignment: center
    line_break: false
sheets:
  - sheet_name: Employees
    update_date_format: small_fmt
    groups:
      - group_name: Employee
        background_color: 4F81BD
      - group_name: Employment Details
        background_color: C0504D
    columns:
      - column_name: id
        variable_name: employee_id
        cell_format: normal_fmt
        group: Employee
        column_width: 6
      - column_name: Name
        variable_name: employee_name
        cell_format: normal_fmt
        group: Employee
        column_width: 14
      - column_name: Department
        variable_name: department
        cell_format: normal_fmt
        group: Employment Details
        column_width: 14
      - column_name: Job Title
        variable_name: job_title
        cell_format: normal_fmt
        group: Employment Details
        column_width: 12
  - sheet_name: Employees Performance
    update_date_format: small_fmt
    groups:
      - group_name: Employee
        background_color: 4F81BD
      - group_name: Sales (kUSD)
        background_color: 8064A2
    columns:
      - column_name: id
        variable_name: employee_id
        cell_format: normal_fmt
        group: Employee
        column_width: 6
      - column_name: Current Year
        variable_name: sales_current_year
        cell_format: normal_fmt
        group: Sales (kUSD)
        column_width: 15
      - column_name: Last Year
        variable_name: sales_last_year
        cell_format: normal_fmt
        group: Sales (kUSD)
        column_width: 15
